//HintName: TelemetryGenerationAttribute.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#if PURVIEW_TELEMETRY_EMBED_ATTRIBUTES

namespace Purview.Telemetry;

[AttributeUsage(AttributeTargets.Assembly | AttributeTargets.Interface, AllowMultiple = false)]
[System.Diagnostics.Conditional(Constants.EmbedAttributesHashDefineName)]
[System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1019:Define accessors for attribute arguments")]
sealed class TelemetryGenerationAttribute : Attribute {
	public TelemetryGenerationAttribute() {
	}

	public TelemetryGenerationAttribute(bool generateDependencyExtension, string classNameTemplate = Constants.Shared.ClassNameTemplateDefault) {
		GenerateDependencyExtension = generateDependencyExtension;
		ClassNameTemplate = classNameTemplate ?? throw new ArgumentNullException(nameof(classNameTemplate));
	}

	public bool GenerateDependencyExtension { get; set; } = Constants.Shared.GenerateDependencyExtensionDefault;

	/// <summary>
	/// <![CDATA[
	/// Replacement options:
	/// <ul>
	///     <li>{GeneratedClassName} the generated class</li>
	///     <li>{InterfaceName} the source interface name</li>
	/// </ul>
	/// ]]>
	/// </summary>
	public string ClassNameTemplate { get; set; } = Constants.Shared.ClassNameTemplateDefault;
}

#endif
