//HintName: Testing.TestMetricsCore.Metric.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class TestMetricsCore : Testing.ITestMetrics
	{
		readonly System.Diagnostics.Metrics.Counter<System.Int32> _counterInstrument;
		readonly System.Diagnostics.Metrics.Counter<System.Int32> _counter2Instrument;
		readonly System.Diagnostics.Metrics.Counter<System.Int32> _counter3Instrument;
		readonly System.Diagnostics.Metrics.Counter<System.Int32> _counter4Instrument;

		public TestMetricsCore(System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			System.Collections.Generic.Dictionary<string, object?> meterTags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateMeterTags(meterTags);

			System.Diagnostics.Metrics.Meter meter = meterFactory.Create(new System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

			_counterInstrument = meter.CreateCounter<System.Int32>(name: "Counter", unit: null, description: null, tags: null);
			_counter2Instrument = meter.CreateCounter<System.Int32>(name: "Counter2", unit: null, description: null, tags: null);
			_counter3Instrument = meter.CreateCounter<System.Int32>(name: "Counter3", unit: null, description: null, tags: null);
			_counter4Instrument = meter.CreateCounter<System.Int32>(name: "Counter4", unit: null, description: null, tags: null);
		}
	}
}
