//HintName: Testing.TestActivitiesCore.Activity.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class TestActivitiesCore : Testing.ITestActivities
	{
		readonly static System.Diagnostics.ActivitySource _activitySource = new System.Diagnostics.ActivitySource("testing-activity-source");

		public void Context(System.Diagnostics.Activity activityParameter, string? stringParam, int? intParam, bool? boolParam)
		{
			if (activityParameter != null)
			{
				activityParameter.SetTag("intparam", intParam);
				activityParameter.SetTag("boolparam", boolParam);
				activityParameter.SetBaggage("stringparam", stringParam);
			}
		}

		public void ContextWithNullableParams(System.Diagnostics.Activity? activityParameter, string? stringParam, int? intParam, bool? boolParam)
		{
			if (activityParameter != null)
			{
				activityParameter.SetTag("intparam", intParam);
				activityParameter.SetTag("boolparam", boolParam);
				activityParameter.SetBaggage("stringparam", stringParam);
			}
		}

	}
}
