//HintName: ServiceTelemetryCore.Metric.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
sealed partial class ServiceTelemetryCore : global::IServiceTelemetry
{
	global::System.Diagnostics.Metrics.Meter _meter = default!;

	global::System.Diagnostics.Metrics.Counter<int>? _anAutoIncrementInstrument = null;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	public ServiceTelemetryCore(global::Microsoft.Extensions.Logging.ILogger<global::IServiceTelemetry> logger, global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
	{
		_logger = logger;
		InitializeMeters(meterFactory);
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	void InitializeMeters(global::System.Diagnostics.Metrics.IMeterFactory meterFactory)
	{
		if (_meter != null)
		{
			throw new global::System.Exception("The meters have already been initialized.");
		}

		global::System.Collections.Generic.Dictionary<string, object?> meterTags = new();

		PopulateMeterTags(meterTags);

		_meter = meterFactory.Create(new global::System.Diagnostics.Metrics.MeterOptions("ServiceTelemetry")
		{
			Version = null,
			Tags = meterTags
		});

		global::System.Collections.Generic.Dictionary<string, object?> anAutoIncrementTags = new();

		PopulateAnAutoIncrementTags(anAutoIncrementTags);

		_anAutoIncrementInstrument = _meter.CreateCounter<int>(name: "anautoincrement", unit: null, description: null, tags: anAutoIncrementTags);
	}

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateMeterTags(global::System.Collections.Generic.Dictionary<string, object?> meterTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	partial void PopulateAnAutoIncrementTags(global::System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void AnAutoIncrement(int value)
	{
		if (_anAutoIncrementInstrument == null)
		{
			return;
		}

		global::System.Diagnostics.TagList anAutoIncrementTagList = new();

		anAutoIncrementTagList.Add("value", value);

		_anAutoIncrementInstrument.Add(1, tagList: anAutoIncrementTagList);
	}
}
