//HintName: Testing.TestActivitiesCore.Activity.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class TestActivitiesCore : Testing.ITestActivities
	{
		readonly static System.Diagnostics.ActivitySource _activitySource = new System.Diagnostics.ActivitySource("testing-activity-source");

		public System.Diagnostics.Activity Context(string? stringParam, int? intParam, bool? boolParam)
		{
			if (System.Diagnostics.Activity.Current != null)
			{
				System.Diagnostics.Activity.Current.SetTag("intparam", intParam);
				System.Diagnostics.Activity.Current.SetTag("boolparam", boolParam);
				System.Diagnostics.Activity.Current.SetBaggage("stringparam", stringParam);
			}

			return System.Diagnostics.Activity.Current;
		}

		public System.Diagnostics.Activity? ContextWithNullableParams(string? stringParam, int? intParam, bool? boolParam)
		{
			if (System.Diagnostics.Activity.Current != null)
			{
				System.Diagnostics.Activity.Current.SetTag("intparam", intParam);
				System.Diagnostics.Activity.Current.SetTag("boolparam", boolParam);
				System.Diagnostics.Activity.Current.SetBaggage("stringparam", stringParam);
			}

			return System.Diagnostics.Activity.Current;
		}

	}
}
