//HintName: EntityStoreTelemetryCore.Metric.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

sealed partial class EntityStoreTelemetryCore : IEntityStoreTelemetry
{
	System.Diagnostics.Metrics.Meter _meter = default!;

	System.Diagnostics.Metrics.Counter<int>? _retrievingEntityInstrument = null;

	public EntityStoreTelemetryCore(Microsoft.Extensions.Logging.ILogger<IEntityStoreTelemetry> logger
#if NET8_0_OR_GREATER
, 		System.Diagnostics.Metrics.IMeterFactory meterFactory
#endif
	)
	{
		_logger = logger;
		InitializeMeters(
#if NET8_0_OR_GREATER
			meterFactory
#endif
		);
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	void InitializeMeters(
#if NET8_0_OR_GREATER
		System.Diagnostics.Metrics.IMeterFactory meterFactory
#endif
	)
	{
		if (_meter != null)
		{
			throw new System.Exception("The meters have already been initialized.");
		}

#if NET8_0_OR_GREATER
		System.Collections.Generic.Dictionary<string, object?> meterTags = new System.Collections.Generic.Dictionary<string, object?>();

		PopulateMeterTags(meterTags);
#endif

		_meter = 
#if NET8_0_OR_GREATER
			meterFactory.Create(new System.Diagnostics.Metrics.MeterOptions("EntityStoreTelemetry")
			{
				Version = null,
				Tags = meterTags
			});
#else
			new System.Diagnostics.Metrics.Meter(name: "EntityStoreTelemetry", version: null);
#endif

#if !NET7_0

		System.Collections.Generic.Dictionary<string, object?> retrievingEntityTags = new System.Collections.Generic.Dictionary<string, object?>();

		PopulateRetrievingEntityTags(retrievingEntityTags);

#endif

		_retrievingEntityInstrument = _meter.CreateCounter<int>(name: "retrievingentity", unit: null, description: null
#if !NET7_0
			, tags: retrievingEntityTags
#endif
		);
	}

#if NET8_0_OR_GREATER

	partial void PopulateMeterTags(System.Collections.Generic.Dictionary<string, object?> meterTags);

#endif

#if !NET7_0

	partial void PopulateGettingEntityFromStoreTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	partial void PopulateGetDurationTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	partial void PopulateRetrievedEntityTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	partial void PopulateProcessingEntityTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	partial void PopulateRetrievingEntityTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

#endif

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void RetrievingEntity(int entityId)
	{
		if (_retrievingEntityInstrument == null)
		{
			return;
		}

		System.Diagnostics.TagList retrievingEntityTagList = new System.Diagnostics.TagList();

		retrievingEntityTagList.Add("entityid", entityId);

		_retrievingEntityInstrument.Add(1, tagList: retrievingEntityTagList);
	}
}
