//HintName: ServiceTelemetryCore.Activity.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

sealed partial class ServiceTelemetryCore : IServiceTelemetry
{
	readonly static System.Diagnostics.ActivitySource _activitySource = new System.Diagnostics.ActivitySource("multi-targeting");

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	static void RecordExceptionInternal(System.Diagnostics.Activity? activity, System.Exception? exception, bool escape)
	{
		if (activity == null || exception == null)
		{
			return;
		}

		System.Diagnostics.ActivityTagsCollection tagsCollection = new System.Diagnostics.ActivityTagsCollection();
		tagsCollection.Add("exception.escaped", escape);
		tagsCollection.Add("exception.message", exception.Message);
		tagsCollection.Add("exception.type", exception.GetType().FullName);
		tagsCollection.Add("exception.stacktrace", exception.StackTrace);

		System.Diagnostics.ActivityEvent recordExceptionEvent = new System.Diagnostics.ActivityEvent(name: "exception", timestamp: default, tags: tagsCollection);

		activity.AddEvent(recordExceptionEvent);
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public System.Diagnostics.Activity? StartAnActivity(int tagIntParam, string entityId)
	{
		if (!_activitySource.HasListeners())
		{
			return null;
		}

		System.Diagnostics.Activity? activityStartAnActivity = _activitySource.StartActivity(name: "StartAnActivity", kind: System.Diagnostics.ActivityKind.Internal, parentId: default, tags: default, links: default, startTime: default);

		if (activityStartAnActivity != null)
		{
			activityStartAnActivity.SetTag("tagintparam", tagIntParam);
		}

		if (activityStartAnActivity != null)
		{
			activityStartAnActivity.SetBaggage("entityid", entityId);
		}

		return activityStartAnActivity;
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void AnInterestingEvent(System.Diagnostics.Activity? activity, float aTagValue)
	{
		if (!_activitySource.HasListeners())
		{
			return;
		}

		if (activity != null)
		{
			System.Diagnostics.ActivityTagsCollection tagsCollectionAnInterestingEvent = new System.Diagnostics.ActivityTagsCollection();
			tagsCollectionAnInterestingEvent.Add("atagvalue", aTagValue);

			System.Diagnostics.ActivityEvent activityEventAnInterestingEvent = new System.Diagnostics.ActivityEvent(name: "AnInterestingEvent", timestamp: default, tags: tagsCollectionAnInterestingEvent);

			activity.AddEvent(activityEventAnInterestingEvent);
		}
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void InterestingInfo(System.Diagnostics.Activity? activity, float anotherTagValue, int intTagValue)
	{
		if (!_activitySource.HasListeners())
		{
			return;
		}

		if (activity != null)
		{
			activity.SetTag("anothertagvalue", anotherTagValue);
			activity.SetTag("inttagvalue", intTagValue);
		}
	}

}
