//HintName: Testing.TestLoggerCoreDIExtension.DependencyInjection.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Microsoft.Extensions.DependencyInjection
{
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
	[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
	static class TestLoggerCoreDIExtension
	{
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddTestLogger(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
		{
			return services.AddSingleton<global::Testing.ITestLogger, global::Testing.TestLoggerCore>();
		}
	}
}
