//HintName: Testing.TestMetricsCore.Metric.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class TestMetricsCore : Testing.ITestMetrics
	{
		System.Diagnostics.Metrics.Meter _meter = default!;

		System.Diagnostics.Metrics.Counter<int>? _counter1Instrument = null;
		System.Diagnostics.Metrics.Counter<int>? _counter2Instrument = null;
		System.Diagnostics.Metrics.Counter<int>? _counter3Instrument = null;

		public TestMetricsCore(System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			InitializeMeters(meterFactory);
		}

		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		void InitializeMeters(System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			if (_meter != null)
			{
				throw new System.Exception("The meters have already been initialized.");
			}

			System.Collections.Generic.Dictionary<string, object?> meterTags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

			System.Collections.Generic.Dictionary<string, object?> counter1Tags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateCounter1Tags(counter1Tags);

			_counter1Instrument = _meter.CreateCounter<int>(name: "counter1", unit: null, description: null, tags: counter1Tags);
			System.Collections.Generic.Dictionary<string, object?> counter2Tags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateCounter2Tags(counter2Tags);

			_counter2Instrument = _meter.CreateCounter<int>(name: "counter2", unit: null, description: null, tags: counter2Tags);
			System.Collections.Generic.Dictionary<string, object?> counter3Tags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateCounter3Tags(counter3Tags);

			_counter3Instrument = _meter.CreateCounter<int>(name: "counter3", unit: null, description: null, tags: counter3Tags);
		}

		partial void PopulateMeterTags(System.Collections.Generic.Dictionary<string, object?> meterTags);

		partial void PopulateCounter1Tags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		partial void PopulateCounter2Tags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		partial void PopulateCounter3Tags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Counter1(int intParam, bool boolParam)
		{
			if (_counter1Instrument == null)
			{
				return;
			}

			System.Diagnostics.TagList counter1TagList = new System.Diagnostics.TagList();

			counter1TagList.Add("intparam", intParam);
			counter1TagList.Add("boolparam", boolParam);

			_counter1Instrument.Add(1, tagList: counter1TagList);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Counter2(int intParam, bool boolParam)
		{
			if (_counter2Instrument == null)
			{
				return;
			}

			System.Diagnostics.TagList counter2TagList = new System.Diagnostics.TagList();

			counter2TagList.Add("intparam", intParam);
			counter2TagList.Add("boolparam", boolParam);

			_counter2Instrument.Add(1, tagList: counter2TagList);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Counter3(int intParam, bool boolParam)
		{
			if (_counter3Instrument == null)
			{
				return;
			}

			System.Diagnostics.TagList counter3TagList = new System.Diagnostics.TagList();

			counter3TagList.Add("intparam", intParam);
			counter3TagList.Add("boolparam", boolParam);

			_counter3Instrument.Add(1, tagList: counter3TagList);
		}
	}
}
