//HintName: MeterTelemetryCore.Metric.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

sealed partial class MeterTelemetryCore : IMeterTelemetry
{
	System.Diagnostics.Metrics.Meter _meter = default!;

	System.Diagnostics.Metrics.Counter<int>? _autoCounterMeterInstrument = null;
	System.Diagnostics.Metrics.Counter<int>? _autoIncrementMeterInstrument = null;
	System.Diagnostics.Metrics.Counter<int>? _counterMeterInstrument = null;
	System.Diagnostics.Metrics.Histogram<int>? _histogramMeterInstrument = null;
	System.Diagnostics.Metrics.ObservableCounter<float>? _observableCounterMeterInstrument = null;
	System.Diagnostics.Metrics.ObservableGauge<float>? _observableGaugeMeterInstrument = null;
	System.Diagnostics.Metrics.ObservableUpDownCounter<byte>? _observableUpDownCounterInstrument = null;
	System.Diagnostics.Metrics.UpDownCounter<decimal>? _upDownCounterMeterInstrument = null;

	public MeterTelemetryCore(System.Diagnostics.Metrics.IMeterFactory meterFactory)
	{
		InitializeMeters(meterFactory);
	}

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	void InitializeMeters(System.Diagnostics.Metrics.IMeterFactory meterFactory)
	{
		if (_meter != null)
		{
			throw new System.Exception("The meters have already been initialized.");
		}

		System.Collections.Generic.Dictionary<string, object?> meterTags = new System.Collections.Generic.Dictionary<string, object?>();

		PopulateMeterTags(meterTags);

		_meter = meterFactory.Create(new System.Diagnostics.Metrics.MeterOptions("MeterTelemetry")
		{
			Version = null,
			Tags = meterTags
		});

		System.Collections.Generic.Dictionary<string, object?> autoCounterMeterTags = new System.Collections.Generic.Dictionary<string, object?>();

		PopulateAutoCounterMeterTags(autoCounterMeterTags);

		_autoCounterMeterInstrument = _meter.CreateCounter<int>(name: "autocountermeter", unit: null, description: null, tags: autoCounterMeterTags);
		System.Collections.Generic.Dictionary<string, object?> autoIncrementMeterTags = new System.Collections.Generic.Dictionary<string, object?>();

		PopulateAutoIncrementMeterTags(autoIncrementMeterTags);

		_autoIncrementMeterInstrument = _meter.CreateCounter<int>(name: "autoincrementmeter", unit: null, description: null, tags: autoIncrementMeterTags);
		System.Collections.Generic.Dictionary<string, object?> counterMeterTags = new System.Collections.Generic.Dictionary<string, object?>();

		PopulateCounterMeterTags(counterMeterTags);

		_counterMeterInstrument = _meter.CreateCounter<int>(name: "countermeter", unit: null, description: null, tags: counterMeterTags);
		System.Collections.Generic.Dictionary<string, object?> histogramMeterTags = new System.Collections.Generic.Dictionary<string, object?>();

		PopulateHistogramMeterTags(histogramMeterTags);

		_histogramMeterInstrument = _meter.CreateHistogram<int>(name: "histogrammeter", unit: null, description: null, tags: histogramMeterTags);
		System.Collections.Generic.Dictionary<string, object?> upDownCounterMeterTags = new System.Collections.Generic.Dictionary<string, object?>();

		PopulateUpDownCounterMeterTags(upDownCounterMeterTags);

		_upDownCounterMeterInstrument = _meter.CreateUpDownCounter<decimal>(name: "updowncountermeter", unit: null, description: null, tags: upDownCounterMeterTags);
	}

	partial void PopulateMeterTags(System.Collections.Generic.Dictionary<string, object?> meterTags);

	partial void PopulateAutoCounterMeterTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	partial void PopulateAutoIncrementMeterTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	partial void PopulateCounterMeterTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	partial void PopulateHistogramMeterTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	partial void PopulateUpDownCounterMeterTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void AutoCounterMeter(string someValue)
	{
		if (_autoCounterMeterInstrument == null)
		{
			return;
		}

		System.Diagnostics.TagList autoCounterMeterTagList = new System.Diagnostics.TagList();

		autoCounterMeterTagList.Add("somevalue", someValue);

		_autoCounterMeterInstrument.Add(1, tagList: autoCounterMeterTagList);
	}
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void AutoIncrementMeter(string someValue)
	{
		if (_autoIncrementMeterInstrument == null)
		{
			return;
		}

		System.Diagnostics.TagList autoIncrementMeterTagList = new System.Diagnostics.TagList();

		autoIncrementMeterTagList.Add("somevalue", someValue);

		_autoIncrementMeterInstrument.Add(1, tagList: autoIncrementMeterTagList);
	}
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void CounterMeter(int measurement, float someValue)
	{
		if (_counterMeterInstrument == null)
		{
			return;
		}

		System.Diagnostics.TagList counterMeterTagList = new System.Diagnostics.TagList();

		counterMeterTagList.Add("somevalue", someValue);

		_counterMeterInstrument.Add(measurement, tagList: counterMeterTagList);
	}
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void HistogramMeter(int measurement, int someValue, bool anotherValue)
	{
		if (_histogramMeterInstrument == null)
		{
			return;
		}

		System.Diagnostics.TagList histogramMeterTagList = new System.Diagnostics.TagList();

		histogramMeterTagList.Add("somevalue", someValue);
		histogramMeterTagList.Add("anothervalue", anotherValue);

		_histogramMeterInstrument.Record(measurement, tagList: histogramMeterTagList);
	}
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void ObservableCounterMeter(System.Func<float> measurement, double someValue)
	{
		if (_observableCounterMeterInstrument != null)
		{
			return;
		}

		System.Diagnostics.TagList observableCounterMeterTagList = new System.Diagnostics.TagList();

		observableCounterMeterTagList.Add("somevalue", someValue);

		_observableCounterMeterInstrument = _meter.CreateObservableCounter<float>("observablecountermeter", measurement, unit: null, description: null
			, tags: observableCounterMeterTagList
		);
	}
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void ObservableGaugeMeter(System.Func<System.Diagnostics.Metrics.Measurement<float>> measurement, double someValue)
	{
		if (_observableGaugeMeterInstrument != null)
		{
			return;
		}

		System.Diagnostics.TagList observableGaugeMeterTagList = new System.Diagnostics.TagList();

		observableGaugeMeterTagList.Add("somevalue", someValue);

		_observableGaugeMeterInstrument = _meter.CreateObservableGauge<float>("observablegaugemeter", measurement, unit: null, description: null
			, tags: observableGaugeMeterTagList
		);
	}
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void ObservableUpDownCounter(System.Func<System.Collections.Generic.IEnumerable<System.Diagnostics.Metrics.Measurement<byte>>> measurement, double someValue)
	{
		if (_observableUpDownCounterInstrument != null)
		{
			return;
		}

		System.Diagnostics.TagList observableUpDownCounterTagList = new System.Diagnostics.TagList();

		observableUpDownCounterTagList.Add("somevalue", someValue);

		_observableUpDownCounterInstrument = _meter.CreateObservableUpDownCounter<byte>("observableupdowncounter", measurement, unit: null, description: null
			, tags: observableUpDownCounterTagList
		);
	}
	[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
	public void UpDownCounterMeter(decimal measurement, byte someValue)
	{
		if (_upDownCounterMeterInstrument == null)
		{
			return;
		}

		System.Diagnostics.TagList upDownCounterMeterTagList = new System.Diagnostics.TagList();

		upDownCounterMeterTagList.Add("somevalue", someValue);

		_upDownCounterMeterInstrument.Add(measurement, tagList: upDownCounterMeterTagList);
	}
}
