//HintName: Testing.TestMetricsCore.Metric.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Testing
{
	sealed partial class TestMetricsCore : Testing.ITestMetrics
	{
		System.Diagnostics.Metrics.Meter _meter = default!;

		System.Diagnostics.Metrics.Counter<int>? _autoCounterInstrument = null;
		System.Diagnostics.Metrics.Counter<int>? _counter_AutoIncrementInstrument = null;
		System.Diagnostics.Metrics.Counter<int>? _counterInstrument = null;
		System.Diagnostics.Metrics.Histogram<int>? _histogramInstrument = null;
		System.Diagnostics.Metrics.UpDownCounter<int>? _upDownCounterInstrument = null;
		System.Diagnostics.Metrics.ObservableCounter<int>? _observableCounterInstrument = null;
		System.Diagnostics.Metrics.ObservableGauge<int>? _observableGaugeInstrument = null;
		System.Diagnostics.Metrics.ObservableUpDownCounter<int>? _observableUpDownCounterInstrument = null;

		public TestMetricsCore(System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			InitializeMeters(meterFactory);
		}

		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		void InitializeMeters(System.Diagnostics.Metrics.IMeterFactory meterFactory)
		{
			if (_meter != null)
			{
				throw new System.Exception("The meters have already been initialized.");
			}

			System.Collections.Generic.Dictionary<string, object?> meterTags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateMeterTags(meterTags);

			_meter = meterFactory.Create(new System.Diagnostics.Metrics.MeterOptions("testing-meter")
			{
				Version = null,
				Tags = meterTags
			});

			System.Collections.Generic.Dictionary<string, object?> autoCounterTags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateAutoCounterTags(autoCounterTags);

			_autoCounterInstrument = _meter.CreateCounter<int>(name: "autocounter", unit: null, description: null, tags: autoCounterTags);
			System.Collections.Generic.Dictionary<string, object?> counter_AutoIncrementTags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateCounter_AutoIncrementTags(counter_AutoIncrementTags);

			_counter_AutoIncrementInstrument = _meter.CreateCounter<int>(name: "counter_autoincrement", unit: null, description: null, tags: counter_AutoIncrementTags);
			System.Collections.Generic.Dictionary<string, object?> counterTags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateCounterTags(counterTags);

			_counterInstrument = _meter.CreateCounter<int>(name: "counter", unit: null, description: null, tags: counterTags);
			System.Collections.Generic.Dictionary<string, object?> histogramTags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateHistogramTags(histogramTags);

			_histogramInstrument = _meter.CreateHistogram<int>(name: "histogram", unit: null, description: null, tags: histogramTags);
			System.Collections.Generic.Dictionary<string, object?> upDownCounterTags = new System.Collections.Generic.Dictionary<string, object?>();

			PopulateUpDownCounterTags(upDownCounterTags);

			_upDownCounterInstrument = _meter.CreateUpDownCounter<int>(name: "updowncounter", unit: null, description: null, tags: upDownCounterTags);
		}

		partial void PopulateMeterTags(System.Collections.Generic.Dictionary<string, object?> meterTags);

		partial void PopulateAutoCounterTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		partial void PopulateCounter_AutoIncrementTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		partial void PopulateCounterTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		partial void PopulateHistogramTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		partial void PopulateUpDownCounterTags(System.Collections.Generic.Dictionary<string, object?> instrumentTags);

		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void AutoCounter(System.Collections.Generic.IDictionary<string, int> genericParameter)
		{
			if (_autoCounterInstrument == null)
			{
				return;
			}

			System.Diagnostics.TagList autoCounterTagList = new System.Diagnostics.TagList();

			autoCounterTagList.Add("genericparameter", genericParameter);

			_autoCounterInstrument.Add(1, tagList: autoCounterTagList);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Counter_AutoIncrement(System.Collections.Generic.IDictionary<string, int> genericParameter)
		{
			if (_counter_AutoIncrementInstrument == null)
			{
				return;
			}

			System.Diagnostics.TagList counter_AutoIncrementTagList = new System.Diagnostics.TagList();

			counter_AutoIncrementTagList.Add("genericparameter", genericParameter);

			_counter_AutoIncrementInstrument.Add(1, tagList: counter_AutoIncrementTagList);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Counter(int value, System.Collections.Generic.IDictionary<string, int> genericParameter)
		{
			if (_counterInstrument == null)
			{
				return;
			}

			System.Diagnostics.TagList counterTagList = new System.Diagnostics.TagList();

			counterTagList.Add("genericparameter", genericParameter);

			_counterInstrument.Add(value, tagList: counterTagList);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void Histogram(int value, System.Collections.Generic.IDictionary<string, int> genericParameter)
		{
			if (_histogramInstrument == null)
			{
				return;
			}

			System.Diagnostics.TagList histogramTagList = new System.Diagnostics.TagList();

			histogramTagList.Add("genericparameter", genericParameter);

			_histogramInstrument.Record(value, tagList: histogramTagList);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void UpDownCounter(int value, System.Collections.Generic.IDictionary<string, int> genericParameter)
		{
			if (_upDownCounterInstrument == null)
			{
				return;
			}

			System.Diagnostics.TagList upDownCounterTagList = new System.Diagnostics.TagList();

			upDownCounterTagList.Add("genericparameter", genericParameter);

			_upDownCounterInstrument.Add(value, tagList: upDownCounterTagList);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableCounter(System.Func<int> valueFunc, System.Collections.Generic.IDictionary<string, int> genericParameter)
		{
			if (_observableCounterInstrument != null)
			{
				return;
			}

			System.Diagnostics.TagList observableCounterTagList = new System.Diagnostics.TagList();

			observableCounterTagList.Add("genericparameter", genericParameter);

			_observableCounterInstrument = _meter.CreateObservableCounter<int>("observablecounter", valueFunc, unit: null, description: null
				, tags: observableCounterTagList
			);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableGauge(System.Func<int> valueFunc, System.Collections.Generic.IDictionary<string, int> genericParameter)
		{
			if (_observableGaugeInstrument != null)
			{
				return;
			}

			System.Diagnostics.TagList observableGaugeTagList = new System.Diagnostics.TagList();

			observableGaugeTagList.Add("genericparameter", genericParameter);

			_observableGaugeInstrument = _meter.CreateObservableGauge<int>("observablegauge", valueFunc, unit: null, description: null
				, tags: observableGaugeTagList
			);
		}
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ObservableUpDownCounter(System.Func<int> valueFunc, System.Collections.Generic.IDictionary<string, int> genericParameter)
		{
			if (_observableUpDownCounterInstrument != null)
			{
				return;
			}

			System.Diagnostics.TagList observableUpDownCounterTagList = new System.Diagnostics.TagList();

			observableUpDownCounterTagList.Add("genericparameter", genericParameter);

			_observableUpDownCounterInstrument = _meter.CreateObservableUpDownCounter<int>("observableupdowncounter", valueFunc, unit: null, description: null
				, tags: observableUpDownCounterTagList
			);
		}
	}
}
