//HintName: ActivityTelemetryCore.DependencyInjection.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Microsoft.Extensions.DependencyInjection
{
	[System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
	static class ActivityTelemetryCore
	{
		[System.Runtime.CompilerServices.MethodImpl(System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		static public Microsoft.Extensions.DependencyInjection.IServiceCollection AddIActivityTelemetry(this Microsoft.Extensions.DependencyInjection.IServiceCollection services)
		{
			services.Add(new Microsoft.Extensions.DependencyInjection.ServiceDescriptor(typeof(IActivityTelemetry), typeof(ActivityTelemetryCore), Microsoft.Extensions.DependencyInjection.ServiceLifetime.Singleton));

			return services;
		}
	}
}
