//HintName: Purview.Interfaces.ApplicationServices.Caching.CacheServiceProviderTelemetryCore.Activity.g.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Purview.Telemetry.SourceGenerator
//     on {Scrubbed}.
//
//     Changes to this file may cause incorrect behaviour and will be lost
//     when the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591 // publicly visible type or member must be documented

#nullable enable

namespace Purview.Interfaces.ApplicationServices.Caching
{
	sealed partial class CacheServiceProviderTelemetryCore : global::Purview.Interfaces.ApplicationServices.Caching.ICacheServiceProviderTelemetry
	{
		readonly static global::System.Diagnostics.ActivitySource _activitySource = new("purview.telemetry.sourcegenerator");

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		static void RecordExceptionInternal(global::System.Diagnostics.Activity? activity, global::System.Exception? exception, bool escape)
		{
			if (activity == null || exception == null)
			{
				return;
			}

			global::System.Diagnostics.ActivityTagsCollection tagsCollection = new();			tagsCollection.Add("exception.escaped", escape);
			tagsCollection.Add("exception.message", exception.Message);
			tagsCollection.Add("exception.type", exception.GetType().FullName);
			tagsCollection.Add("exception.stacktrace", exception.StackTrace);

			global::System.Diagnostics.ActivityEvent recordExceptionEvent = new(name: "exception", timestamp: default, tags: tagsCollection);

			activity.AddEvent(recordExceptionEvent);
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public System.Diagnostics.Activity? GetFromCache()
		{
			if (!_activitySource.HasListeners())
			{
				return null;
			}

			global::System.Diagnostics.Activity? activityGetFromCache = _activitySource.StartActivity(name: "GetFromCache", kind: global::System.Diagnostics.ActivityKind.Client, parentId: default, tags: default, links: default, startTime: default);

			return activityGetFromCache;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void NoValueProvided()
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (System.Diagnostics.Activity.Current != null)
			{

				global::System.Diagnostics.ActivityEvent activityEventNoValueProvided = new(name: "NoValueProvided", timestamp: default, tags: default);

				System.Diagnostics.Activity.Current.AddEvent(activityEventNoValueProvided);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public System.Diagnostics.Activity? SerializePayload()
		{
			if (!_activitySource.HasListeners())
			{
				return null;
			}

			global::System.Diagnostics.Activity? activitySerializePayload = _activitySource.StartActivity(name: "SerializePayload", kind: global::System.Diagnostics.ActivityKind.Internal, parentId: default, tags: default, links: default, startTime: default);

			return activitySerializePayload;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void SerializePayloadResult(int payloadStringLength)
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (System.Diagnostics.Activity.Current != null)
			{
				System.Diagnostics.Activity.Current.SetTag("payloadstringlength", payloadStringLength);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public System.Diagnostics.Activity? SetInCache()
		{
			if (!_activitySource.HasListeners())
			{
				return null;
			}

			global::System.Diagnostics.Activity? activitySetInCache = _activitySource.StartActivity(name: "SetInCache", kind: global::System.Diagnostics.ActivityKind.Client, parentId: default, tags: default, links: default, startTime: default);

			return activitySetInCache;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void SetDefaultTags(string distributedCacheType, string cacheKey, string? entityType)
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (System.Diagnostics.Activity.Current != null)
			{
				System.Diagnostics.Activity.Current.SetTag("distributedcachetype", distributedCacheType);
				System.Diagnostics.Activity.Current.SetTag("cachekey", cacheKey);
				System.Diagnostics.Activity.Current.SetTag("entitytype", entityType);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void ValueCached()
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (System.Diagnostics.Activity.Current != null)
			{

				global::System.Diagnostics.ActivityEvent activityEventValueCached = new(name: "ValueCached", timestamp: default, tags: default);

				System.Diagnostics.Activity.Current.AddEvent(activityEventValueCached);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void RequestingValueFromCache()
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (System.Diagnostics.Activity.Current != null)
			{

				global::System.Diagnostics.ActivityEvent activityEventRequestingValueFromCache = new(name: "RequestingValueFromCache", timestamp: default, tags: default);

				System.Diagnostics.Activity.Current.AddEvent(activityEventRequestingValueFromCache);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void CacheHit(int? dataLength)
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (System.Diagnostics.Activity.Current != null)
			{
				global::System.Diagnostics.ActivityTagsCollection tagsCollectionCacheHit = new();
				tagsCollectionCacheHit.Add("datalength", dataLength);

				global::System.Diagnostics.ActivityEvent activityEventCacheHit = new(name: "CacheHit", timestamp: default, tags: tagsCollectionCacheHit);

				System.Diagnostics.Activity.Current.AddEvent(activityEventCacheHit);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public void CacheMiss()
		{
			if (!_activitySource.HasListeners())
			{
				return;
			}

			if (System.Diagnostics.Activity.Current != null)
			{

				global::System.Diagnostics.ActivityEvent activityEventCacheMiss = new(name: "CacheMiss", timestamp: default, tags: default);

				System.Diagnostics.Activity.Current.AddEvent(activityEventCacheMiss);
			}
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public System.Diagnostics.Activity? DeserializePayload()
		{
			if (!_activitySource.HasListeners())
			{
				return null;
			}

			global::System.Diagnostics.Activity? activityDeserializePayload = _activitySource.StartActivity(name: "DeserializePayload", kind: global::System.Diagnostics.ActivityKind.Internal, parentId: default, tags: default, links: default, startTime: default);

			return activityDeserializePayload;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public System.Diagnostics.Activity? Refresh()
		{
			if (!_activitySource.HasListeners())
			{
				return null;
			}

			global::System.Diagnostics.Activity? activityRefresh = _activitySource.StartActivity(name: "Refresh", kind: global::System.Diagnostics.ActivityKind.Client, parentId: default, tags: default, links: default, startTime: default);

			return activityRefresh;
		}

		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Purview.Telemetry.SourceGenerator", "0.1.0.0")]
		[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
		public System.Diagnostics.Activity? Remove()
		{
			if (!_activitySource.HasListeners())
			{
				return null;
			}

			global::System.Diagnostics.Activity? activityRemove = _activitySource.StartActivity(name: "Remove", kind: global::System.Diagnostics.ActivityKind.Client, parentId: default, tags: default, links: default, startTime: default);

			return activityRemove;
		}

	}
}
